dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
      # Set up git user name and tag this commit
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: toZ57BWFwtfHNAHed7f/O36V+r6Gwqyz7iUz/FtmKIhjjqxCLRZehlizgjxRpUDWpogglz6poBMcL44zTGQh+8difzkisApDTDbB2kiJHbVqvzvN8HE0npadqv77yfi8TCpx5opw5k6aGVvdqrDtrMWkjs5lhScVXnAuWFdaAo5Z0J/6e+olo5+IrjLCYv1OqWYFjm0y84dlKhmEag05C1HDV3qNB5s8ftPkOOX4F8IfcPDt5tJeWzmbnM02mul887VN04X5oauBnEav9iguwv1nM/AaV2MiOGYEorcHd4j2xWyB8WDdUwLe9z5qZe/f5Cm/mtn7oUkFqoCoPm4I8V4GjmkjA0r4QCuejRRIjhaGDF22d+er2hZkhDceyl0orq/yUZ7pD/5+FwxDtrcw/iruecCsbllJ8kEOS3OjdkhNsg6U5Nz7E4ZmQDLcJkk80s2TKziKMAxwnPohGuFpYU6qAKhuaGdbRLmRGYO/BGLuKiZdnevqjE+JHaUfcfYKdC4jHOGVamuCPdGjUS3xSvOMkxPsMD+OpRGvkaBBZgSvUQPwC4n4HvzBFm09hC15sT2P1mmbMn5XybfT4CIY/qxXaqkDxsj9gfBX1jmH7IlVEjQo19UYnkKWAf24W6M2LqMTidntZdPkpRc8GlXJviTGC+BXkAGCO9xcHCIAY+k=
  file: Gerbers/KAT-101_gerbers.zip
  on:
    repo: w4xzr/KAT-101
  skip_cleanup: 'true'
